trigger:
- develop
- merge

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: '0'
  minor: '0'
  patch: '1'
  version: $(major).$(minor).$(patch)

stages:
  - stage: WebApi
    displayName: "Build nad publish WebApi"
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: BuildSolution
        timeoutInMinutes: 30
        workspace: 
          clean: all
        steps:
          - task: NuGetCommand@2
            displayName: "Restoring NuGets"
            inputs:
              command: restore
              restoreSolution: $(solution)
              feedsToUse: select
              versioningScheme: byEnvVar
              versionEnvVar: $(version)
              
          - task: DotNetCoreCLI@2
            displayName: "Building projects"
            inputs:
              command: build
              versioningScheme: byEnvVar
              versionEnvVar: $(version)

          - task: DotNetCoreCLI@2
            displayName: "Running tests"
            inputs:
              command: test
              projects: "**/tests/**/*Tests.csproj"
              arguments: "-- no-build --verbosity quiet"

          - task: DotNetCoreCLI@2
            displayName: "Publishing projects"
            inputs:
              projects: '**/E-Lang.WebApi.csproj'
              arguments: '-o $(Build.ArtifactStagingDirectory)/WebApi'
              zipAfterPublish: true
          
          - task: PublishBuildArtifacts@1
            displayName: "Publishing WebApi"
            condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)/WebApi
              publishWebProjects: true
              publishLocation: Container
              ArtifactName: 'WebApi'
