
using E_Lang.Application.Common.Interfaces.Repositories;
using E_Lang.Domain.Entities;
using Microsoft.Extensions.DependencyInjection;

namespace E_Lang.Seeder.Seeders
{
    public class GreekCollectionSeeder : SeederBase
    {
        private readonly Guid _userId;
        private readonly IQuizTypeRepository _quizTypeRepository;

        private Collection? _unit10;

        public GreekCollectionSeeder(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            _userId = _userService.GetUserId();
            _quizTypeRepository = serviceProvider.GetRequiredService<IQuizTypeRepository>();
        }

        public override async Task Seed()
        {
            await SeedCollection();
            await SeedFlashcards();
        }

        private async Task SeedCollection()
        {
            var firstQuiz = (await _quizTypeRepository.GetAllAsync())
                .FirstOrDefault(x => x.IsFirst)
                ?? throw new NullReferenceException("First quiz not found.");

            var secondQuiz = (await _quizTypeRepository.GetAllAsync())
                .FirstOrDefault(x => !x.IsFirst)
                ?? throw new NullReferenceException("First quiz not found.");

            await Builder
                .AddCollection(out var collection, _userId)
                    .SetName("Modern Greek")
                    .AddSubcollection(out _)
                        .SetName("Modern Greek - A1")
                        .AddSubcollection(out _unit10)
                            .SetName("Unit 10")
                            .AddAttempt(out var _, firstQuiz)
                                .SetName("Default attempt")
                                .SetMaxFlashcardsPerStage(5)
                                .AddQuizType(secondQuiz)
                                .AddInitAttemptStageAsCurrentStage(out var _)
                                    .AddFlashcard(out var _, collection)
                                        .AddFlashcardBase(out var _)
                                            .SetWordOrPhrase("σήμερα")
                                            .AddMeaning(out Meaning _)
                                                .SetValue("dziś; dzisiaj")
                                                .Build()
                                            .AddMeaning(out var _)
                                                .SetValue("obecnie")
                                                .Build()
                                            .Build()
                                        .Build()
                                    .AddFlashcard(out var _, collection)
                                        .AddFlashcardBase(out var _)
                                            .SetWordOrPhrase("νούμερο")
                                            .AddMeaning(out Meaning _)
                                                .SetValue("numer")
                                                .Build()
                                            .AddMeaning(out var _)
                                                .SetValue("rozmiar")
                                                .Build()
                                            .Build()
                                        .Build()
                                    .AddFlashcard(out var _, collection)
                                        .AddFlashcardBase(out var _)
                                            .SetWordOrPhrase("περίοδος")
                                            .AddMeaning(out Meaning _)
                                                .SetValue("okres (czasu)")
                                                .Build()
                                            .AddMeaning(out var _)
                                                .SetValue("[anatomia] okres; menstruacja;")
                                                .Build()
                                            .Build()
                                        .Build()
                                    .AddFlashcard(out var _, collection)
                                        .AddFlashcardBase(out var _)
                                            .SetWordOrPhrase("μέσο")
                                            .AddMeaning(out Meaning _)
                                                .SetValue("środek (np. transportu)")
                                                .Build()
                                            .AddMeaning(out var _)
                                                .SetValue("sposób (np. na coś)")
                                                .Build()
                                            .Build()
                                        .Build()
                                    .AddFlashcard(out var _, collection)
                                        .AddFlashcardBase(out var _)
                                            .SetWordOrPhrase("οδηγός")
                                            .AddMeaning(out Meaning _)
                                                .SetValue("kierowca")
                                                .Build()
                                            .AddMeaning(out var _)
                                                .SetValue("przewodnik [książka]")
                                                .Build()
                                            .AddMeaning(out var _)
                                                .SetValue("przewodnik [człowiek]")
                                                .Build()
                                            .Build()
                                        .Build()
                                    .Build()
                                .Build()
                            .Build()
                        .Build()
                    .Build()
                .SaveAsync();
        }

        private async Task SeedFlashcards()
        {
            await Builder
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("χυμός")
                        .AddMeaning(out var _)
                            .SetValue("sok")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("σοκολάτα")
                        .AddMeaning(out var _)
                            .SetValue("czkolada")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("μηχανή")
                        .AddMeaning(out var _)
                            .SetValue("motocykl")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("skuter")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("silnik")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("aparat (fotograficzny)")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("φακός")
                        .AddMeaning(out var _)
                            .SetValue("latarka")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("obiektyw")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("szkło powiększające")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("soczewka")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("καινούριος")
                        .AddMeaning(out var _)
                            .SetValue("nowy")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("νέος")
                        .AddMeaning(out var _)
                            .SetValue("nowy")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("młody")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("διαβάζω")
                        .AddMeaning(out var _)
                            .SetValue("czytać")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("uczyć się")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("γράμμα")
                        .AddMeaning(out var _)
                            .SetValue("list")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("litera")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("υπολογιστής")
                        .AddMeaning(out var _)
                            .SetValue("komputer")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("kalkulator")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("σταθμός")
                        .AddMeaning(out var _)
                            .SetValue("stacja (radiowa)")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("stacja (kolejowa)")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("stacja (metro)")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("φεύγω")
                        .AddMeaning(out Meaning _)
                            .SetValue("wychodzić")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("uciekać")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("φτηνός")
                        .AddMeaning(out var _)
                            .SetValue("tani")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("κινηματογράφος")
                        .AddMeaning(out var _)
                            .SetValue("kino")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("στενός")
                        .AddMeaning(out Meaning _)
                            .SetValue("wąski")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("ciasny")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("γλώσσα")
                        .AddMeaning(out Meaning _)
                            .SetValue("[anatomia] język")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("[lingwistyka] język")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("sola")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("ακούω")
                        .AddMeaning(out Meaning _)
                            .SetValue("słuchać")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("słyszeć")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("γραφείο")
                        .AddMeaning(out Meaning _)
                            .SetValue("biurko")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("biuro")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("ύπνος")
                        .AddMeaning(out var _)
                            .SetValue("spanie")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("όνειρο")
                        .AddMeaning(out Meaning _)
                            .SetValue("sen")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("marzenie")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("ξέρω")
                        .AddMeaning(out Meaning _)
                            .SetValue("znać")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("umieć")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("wiedzieć")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("ώρα")
                        .AddMeaning(out Meaning _)
                            .SetValue("godzina")
                            .Build()
                        .AddMeaning(out var _)
                            .SetValue("czas (krótki okres czasu)")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("κατάστημα")
                        .AddMeaning(out Meaning _)
                            .SetValue("sklep")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("μαγαζί")
                        .AddMeaning(out Meaning _)
                            .SetValue("sklep")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("μάλιστα")
                        .AddMeaning(out Meaning _)
                            .SetValue("oczywiście")
                            .Build()
                        .Build()
                    .Build()
                .AddFlashcard(out var _, _unit10!.Id, _userId)
                    .AddFlashcardBase(out var _)
                        .SetWordOrPhrase("βεβαίως")
                        .AddMeaning(out Meaning _)
                            .SetValue("oczywiście")
                            .Build()
                        .Build()
                    .Build()
                .SaveAsync();
        }
    }
}
